sudo: false
language: ruby
cache: bundler

rvm:
  - 2.3.1

env:
  - AZURE_VM_NAME="example-01"
  - AZURE_RESOURCE_GROUP_NAME="MyResourceGroup"
  - AZURE_CREDS_FILE=".travis_azure_creds"

bundler_args: --without integration
script: bundle exec rake